apiVersion: v1
kind: Service
metadata:
  name: svc
  namespace: argocd-app  
spec:
  selector:
    app: juice-shop
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
  type: LoadBalancer 
